### PR TITLE
Add sub-resolution proposal

### PR DESCRIPTION
**Pull request by rleigh-codelibre**

### CODE REVIEW

**Comment by joshmoore** [comment]
No objections from my side to starting here as a `v1`. (I also like the subdirectories, but that's one we should agree on since renames won't be redirected as with full repositories.)

**Comment by sbesson** [comment]
Agreed with regard to directories, I can see 2 options:

- `YYYY/MM/<proposal.md` as suggested here
- `nnn/<proposal>.md` where `nnn` is an incremental number

As discussed recently, slight personal preference here for option 2 personally in the anticipation this could eventually turn into something more official like [PEP](https://www.python.org/dev/peps/pep-0440/) and [JEP](http://openjdk.java.net/jeps) where a attribution number helps with the naming. In this case, the creation date could still be captured as internal metadata.

**Comment by sbesson** [comment]
Sounds good. In terms of numbering, we can probably call this one 005. Looking at the history, that would give:

Index | Proposal
------|----------
001 | cli_tree.md
002 | omero_features.md
003 | ansible-omero-roles.md
004 | tiling_scoping.md
005 | tiff_sub_resolution_support.md

Starting the indexing of concrete proposals at 1 so that anyone can use the 0 for the indexing as a RFE.

**Comment by rleigh-codelibre** [comment]
https://github.com/openmicroscopy/design/pull/84 is the renumbering work.

**Pull request merged**
