### PR TITLE
Move design documents into numbered directories

### PR DESCRIPTION
**Pull request by rleigh-codelibre**

### CODE REVIEW

**Comment by manics** [comment]
After this is merged would it be worth adding an index page and creating a `gh-pages` branch?

**Comment by sbesson** [comment]
:+1: for the index page (see https://github.com/openmicroscopy/design/pull/83#issuecomment-363841544). How would you see the `gh-pages` workflow working in terms of rendering of markdown pages, deployment URL and sync with the `master` branch?

**Comment by hflynn** [comment]
Does GitHub pages support building from a master branch now? I thought you didn't need to use gh-pages branches any more if you didn't have another reason for wanting that content on a separate branch

**Comment by mtbc** [comment]
Would it be worth suffixing the numbers with a brief title, "005-washing-the-dishes" or whatever? As it is you type "ls" and see no hint of into where to "cd".

**Comment by manics** [comment]
If you can publish straight off `master` that sounds fine to me

**Comment by hflynn** [comment]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by sbesson** [comment]
Looked into the various options for the discussion above. Publication is definitely doable using the `master` branch on GitHub with native support for Markdown rendering. Main issue is that this might force to rename the files as `index.md` - see http://sbesson.github.io/design/001/ for an example built on top of this branch.

Open questions:
- base URL: without modifications, this would get published at http://openmicrosopy.github.io/design. Is that acceptable or would we want to spin up an official design.openmicroscopy.org URL or similar straight away?
- searching/indexing/metadata: options would be:
     * `nnn/index.md` + capture the metadata in a dedicate index page (`README.md` or `000/index.md`) and/or even as  key/value pairs in the markdown that can be `grep`ed. 
     *<nnn>-<name>/index.md` as proposed in https://github.com/openmicroscopy/design/pull/84#issuecomment-364058303

On the second question, slight personal preference for the first option as this is the scheme used by other known communities, it makes slightly shorter URLs and defined code names (e.g. OME0001 ;) ) and allows us to update the title of a proposal without breaking published URLs. Other thoughts/rationale welcome.

**Comment by rleigh-codelibre** [comment]
The github.io URL seems fine; a CNAME in the DNS is a nice extra, but not essential.

Separate index.md files with a top-level index seems fine to me.  Shall I do that in this PR?

**Comment by sbesson** [comment]
@rleigh-codelibre: feel free to push an additional commit as part of this PR as this also deals with renaming.

**Comment by rleigh-codelibre** [comment]
@sbesson Done.  Please see https://rleigh-codelibre.github.io/design/ for a preview.

**Comment by hflynn** [comment]
Looks nice!

**Comment by joshmoore** [comment]
Very.

**Comment by sbesson** [comment]
Generally, very useful. Although the permanent URLs for these still remains to be defined/polished etc this refactoring provides very strong foundations to discuss/exposing some of these proposals to the wider community. Merging and we can decide on the RFEs separately.

**Pull request merged**
